import org.apache.hadoop.security.proto.RefreshUserMappingsProtocolProtos.RefreshSuperUserGroupsConfigurationRequestProto;
public class FunctionUse13528 {
public void funcUse() {
RefreshSuperUserGroupsConfigurationRequestProto refreshsuperusergroupsconfigurationrequestproto = new RefreshSuperUserGroupsConfigurationRequestProto();
refreshsuperusergroupsconfigurationrequestproto.writeTo(null);
}
}